{% set name = "django-emailhub" %}
{% set version = "0.0.1" %}
{% set sha256 = "24e347b74e99b9d2e9d20c4d349c326e469c47c801d60871ab4fc3a17b3a80eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gitlab.com/h3/{{ name }}/repository/master/archive.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1001
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python <3.6
    - setuptools
    - pip
  run:
    - python <3.6
    - django >=1.8,<=1.11
    - six >=1.11.0

test:
  requires:
    - tox >=2.9.1
  imports:
    - emailhub
    - emailhub.backends
    - emailhub.backends.anymail
    - emailhub.backends.secure_mail
    - emailhub.conf
    - emailhub.management
    - emailhub.migrations
    - emailhub.runtests
    - emailhub.tests
    - emailhub.utils

about:
  home: https://gitlab.com/h3/django-emailhub
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Django EmailHub is an application that bring advanced email functionnalities to Django such as
            templates, draft state, batch sending and archiving.'
  description: 
    Django EmailHub is an application that bring advanced email functionnalities to Django such as
    templates, draft state, batch sending and archiving.
  doc_url: http://django-emailhub.readthedocs.io/
  dev_url: https://gitlab.com/h3/django-emailhub

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
