# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "3IprsJ8bvK8g8emUG5MWeVwbPNgySSss6pCLdPSoW9WU20cBMMAxHX+wPxh/bslHQxCFzoHedY0exmCqDI8fYBWG0z7O76BDkrs8BC7OwmZEvJgdAFFOkkpfKV0EuKfX5NI2614L2TWyVD1xoPMT9T4K7F9J02580tfsNkd78DfCMpt78+ZQ/xRGWadO5ZHAgCRHVGUZ4BQi6Wi8I/rhJw/Fm7YdlwT/nt6Uu7rwN0D7XjHchv9iy7awpADIp18wvvR17Rh26Ie1yt4ZQx83eA8LHyhsOhsHolZgFSioo9W1xJqCXbXIWFDhpFXV8Eu/2mL1H462+BYQvsgkmw08JPfcrCrS5faeVxh6jI++gaj8pvPQk3UosppGvHmEV9PXuJ8VtKwMrPleMiHGUyvXtrCznL4nISA9wPJ562bCMvKf1CLYRuFiduS7n1ibIiZcWbisqGVBGx+IJzrXASMsWepwjcrKdkgajRO6fU7TIfQezYiki9NCV9CABSzxmSw4hzUg8h/K3z3HMam7WD60WmMyVoI3CSNj+zQzZW/aPkh5TAMKIn7Vs3MjpNOTtjQ038DTnE4WzFx+NnmytR4F2rs05DWzAxDV4oVfl9PJ/cjl5RnujAQsFhO1SyaQ9lsek3o3rsrjugCi2Cfh3RHnJsYZNrq9tyIb0dKTe6Tx0SA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
