travis:
  secure:
    BINSTAR_TOKEN: thsCUfLGSILYY19HsrsRmmhlccrsO/QV4dXwaSA2jb1YALhxPqrestBp/oUsAlq+qsW5uZxSZCvFGo9tMKsf0zO3jebt1EuMLr5cluFP9S3Hsca24/sf/WVN+3ZSFcYmP1T71/CoZ9ON6wZYhZyOrNZC9pg1ce1SNQQvrjI79Mf+fU/PHFJfwRvrFTTdtcAELk4JilxfaiVlQM//mmd4N7vMjluHdK+uqTcrqqVIKm+wDP1fP+r5hmsOBJEtAsRhRl0P0hTy+TM4DlMNYQTYFrBBIM0q0EU3WQduGH1u92TDh9fpJfOjMOCxqY026YhMY6m3VqYB3h3dDOYfc3Lo41R1nlHr34oY0RQCl9q3GU35Luml3Vc8iJO+NEVGstqzaDVQozNnQ2VPA5BaY6k2ncvu6DsM9L08xGkIgdWc52ylw7QLE7jQui35xwYdH3C5IcNYqtUHydYzqlDwkEehybPQBHry9PmvpXHpPi/CqdsQbJdo1qRMe1fETZ4E9vMNk6UTRC1cpesuECG97iXXMkR4TH4ByVvB7NAZinPP8YOW1gSYYd5k9prciTNdrzvq/8ED+EIsgHD3EkxyG6osca//3OJQiUp1q3il28mIbZxzw9A+xp9NMULlrUDZioMrDMG8AZvbS8FjKprM7dWP3a46eMAeXbSazL4CHatsL6M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
