appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: s8JBrXoY8uPSVgn8seceHnXlAszwB+urqPebjlBYUa7M7cxURJK4HgbDib7jTI5NBa4ira3JXsKw0bAgR0q+8FlRNJxdTNAkT52Rji0jbzGc1mZdC5RZbjC4+LiGNNS/73JM9Eq27noLUTGqhrXh7jsKg2UkfucP7uRaNZ6oZrBl+2jKuDBJcOT/535m5Vn/QIHPsqzKBkbiAyD0Mi3+VYS2ZzurNQNDvxDQ2zuC0CR6LCCQgrbmDIvJ6ZcH2WlVXP6/M8F5/7HKRPST7cJbdEMg4Qups8ScKh5iCHdVkKwA4WioAiMf1EXLeRzW/e+V25U+0Z9AQxXoCulmKZ+CuHlmJ1mIkctjMtGR2kBYONnmoYr95GWt+mUX1ucgg1Rs5rIDL6EduOEgbJCwnGROQIAMerV2m+Fn5p1OKMi/tFa8SSJ6vRgoLUQ5kg3Dv+QeWbv8XJej4KOI06Z+e9VLURY+KhDri0lilSUj7rbuZMo0ibeUAQOmPnp3LDmSozdwQIdtinvEeiHw5cBm5w1YPA7LenmVf8BzHxL0uoT62QTJgTUArp8FUy/rl9vC+Dp/WmOX0kvu+8RgwLsH0X2WWB5aQF6cGkACtMYldjAqT75j4FDHgy+jnFwIeAnLioikUcoP7nSpGyOlgWowxQHafUC0oUNSfCAPqfv5cT2OSdQ=}
