travis:
  secure:
    BINSTAR_TOKEN: MK7vkk213UDq39CBh8nm0iYIH6x7Ny9CwF9qS2cfRhALfKs6YNJI0lRf/eKGoaXjA7Kf8L+RA/XdLb67xDewryaOlhWx/Ad81ow+SC0i3gdpxHydEEaV+YA0PZESzZ3c362dVgr5kQJnVcbBvGU18fQk70EKIdvKTj4yxSCWHL0fXACQ3fbTSdygBiDY8kwtM0qm00hR0gyAarCuYKH8DhuY3PRpE6KZUa+OgZZTmxnAaC4e+VbtV89LZXIpU6enX7B03fyuVhc+CREU2wTb0b/lgsq1WZ33h/Gkid9vFkph4Vzcxz5C6/X1Q5mE/KUuA6wwHrEixCvoyY0ncvGFYfFTPsSjwHFFOqdyFvt2px0RQZsA275AIGGaBaOyxPORZkDFhI2lMy4ue1TUTJ9vIWgVBu3kq6bj+eic/E9uH62YhdfiwV7uH32SCOwHX4+XeN+VGI2Q6/0Q+K8y2CkmrFUmvOcUfEKWlYRtgCHcdmp1GiDmezU/yV0GRsRgyDLCN/YD2jIVfROgPRx8yiI+iE1fyEp8SNDfGbt0MaPoFoaLFUXe2Si0nQAuSDpsaNvOBH4ZiZXhiIuc0oz93zfpG7mLL6FCN9gupTQvZp0c5yX2pJR9WAKwmpUV71w6ujOkIzDZ7g6wymy7ZLwopRnA9GYycGVQJ4tHUv4KNXE80X8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
