travis:
  secure:
    BINSTAR_TOKEN: 3IprsJ8bvK8g8emUG5MWeVwbPNgySSss6pCLdPSoW9WU20cBMMAxHX+wPxh/bslHQxCFzoHedY0exmCqDI8fYBWG0z7O76BDkrs8BC7OwmZEvJgdAFFOkkpfKV0EuKfX5NI2614L2TWyVD1xoPMT9T4K7F9J02580tfsNkd78DfCMpt78+ZQ/xRGWadO5ZHAgCRHVGUZ4BQi6Wi8I/rhJw/Fm7YdlwT/nt6Uu7rwN0D7XjHchv9iy7awpADIp18wvvR17Rh26Ie1yt4ZQx83eA8LHyhsOhsHolZgFSioo9W1xJqCXbXIWFDhpFXV8Eu/2mL1H462+BYQvsgkmw08JPfcrCrS5faeVxh6jI++gaj8pvPQk3UosppGvHmEV9PXuJ8VtKwMrPleMiHGUyvXtrCznL4nISA9wPJ562bCMvKf1CLYRuFiduS7n1ibIiZcWbisqGVBGx+IJzrXASMsWepwjcrKdkgajRO6fU7TIfQezYiki9NCV9CABSzxmSw4hzUg8h/K3z3HMam7WD60WmMyVoI3CSNj+zQzZW/aPkh5TAMKIn7Vs3MjpNOTtjQ038DTnE4WzFx+NnmytR4F2rs05DWzAxDV4oVfl9PJ/cjl5RnujAQsFhO1SyaQ9lsek3o3rsrjugCi2Cfh3RHnJsYZNrq9tyIb0dKTe6Tx0SA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
